// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk6GqEen_cyiMlKCea-rGUA49oYW_PCf0',
    appId: '1:1071722667674:web:aca0e8bfcc1599d0f70923',
    messagingSenderId: '1071722667674',
    projectId: 'reina-nochebuena',
    authDomain: 'reina-nochebuena.firebaseapp.com',
    storageBucket: 'reina-nochebuena.firebasestorage.app',
    measurementId: 'G-KW84HPF3YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHLX8QCx3xX9feisf1a5iCfJPf-XCOWE8',
    appId: '1:1071722667674:android:a4a383e27a74867ef70923',
    messagingSenderId: '1071722667674',
    projectId: 'reina-nochebuena',
    storageBucket: 'reina-nochebuena.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYKIcAn4LAj348exeLwc2HrAoD72ADFCg',
    appId: '1:1071722667674:ios:a52ab52258e86834f70923',
    messagingSenderId: '1071722667674',
    projectId: 'reina-nochebuena',
    storageBucket: 'reina-nochebuena.firebasestorage.app',
    iosBundleId: 'com.example.reinaNochebuena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYKIcAn4LAj348exeLwc2HrAoD72ADFCg',
    appId: '1:1071722667674:ios:a52ab52258e86834f70923',
    messagingSenderId: '1071722667674',
    projectId: 'reina-nochebuena',
    storageBucket: 'reina-nochebuena.firebasestorage.app',
    iosBundleId: 'com.example.reinaNochebuena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk6GqEen_cyiMlKCea-rGUA49oYW_PCf0',
    appId: '1:1071722667674:web:513f18f008666b45f70923',
    messagingSenderId: '1071722667674',
    projectId: 'reina-nochebuena',
    authDomain: 'reina-nochebuena.firebaseapp.com',
    storageBucket: 'reina-nochebuena.firebasestorage.app',
    measurementId: 'G-KH6EDDP3S6',
  );

}